task:
  task: aq
  property: aq
  loader: AqSolDataset
  filepath: /workspace/data/AqueousSolu.csv
  propname: logS_aq_avg
  smilesname: smiles solute
  plot_title: Aqueous solubility
  plot_propname: log(S)
split:
  split: accurate
  n_splits: 5
  split_frac: 0.9
  data_seed: 42
  color: r
  scale: false
model:
  model: mmb-ft
  finetune: false
  n_batch: 48
  seed: 42
  n_epochs: 30
head:
  head: lin
xai:
  model: mmb-ft
  xai: mmb
  mask: true
  sign: None
  save_heat: false
  cmap: None
